name: Deploy DAB - dev
on:
  push:
    branches:
      - dev
concurrency:
  group: deploy-dev
  cancel-in-progress: false

jobs:
  deploy-dev:
    name: validate & deploy (target dev)
    runs-on: ubuntu-latest

    environment: dev

    env:
      DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
      DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}

    steps:
      - name: Checkout repository # clona o repositorio no runner do github
        uses: actions/checkout@v4

      - name: Set up Python # instala o python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Set up uv #instala o uv
        uses: astral-sh/setup-uv@v5

      - name: Install Databricks CLI # configura o databricks olhando host e token no secrets env
        uses: databricks/setup-cli@main

      - name: Validate bundle (dev) # valida sintaticamente o projeto databricks
        run: databricks bundle validate --target dev

      - name: Deploy bundle (dev) # Faz o deploy para dentro do ambiente databricks
        run: databricks bundle deploy --target dev
